### ISSUE TITLE
Update Arch Linux package

### ISSUE THREAD

**Issue by ekd123** [jckarter/clay#138]
`Scanning dependencies of target clay
[  4%] Building CXX object compiler/src/CMakeFiles/clay.dir/analyzer.cpp.o
In file included from /var/abs/local/yaourtbuild/clay-hg/src/clay/compiler/src/analyzer.cpp:1:0:
/var/abs/local/yaourtbuild/clay-hg/src/clay/compiler/src/clay.hpp:24:38: fatal error: llvm/Target/TargetSelect.h: No such file or directory
compilation terminated.
make[2]: *** [compiler/src/CMakeFiles/clay.dir/analyzer.cpp.o] Error 1
make[1]: *** [compiler/src/CMakeFiles/clay.dir/all] Error 2
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build clay-hg.`

How do i fix it?

**Comment by ghost** [comment]
@ekd123 This AUR package is out of date.

You need to install Clay from the git repository until someone contributes a new AUR clay-git package (I may actually do this soon . . . ).

Note: Clay from jckarter's repository will build OK with the latest llvm/clang (3.0) package in Archlinux, however patches are required to build the bindgen tool.  Patched versions of llvm & clang are available on jckarter's github. I've installed these instead of the Arch packages and it all runs fine.

**Comment by jckarter** [comment]
Thanks for the report, @ekd123 . As agemogolk noted, the Arch Linux package is outdated; it looks like it's pulling from KS's moribund bitbucket repository. If you don't mind, I'll turn this issue into the "update Arch Linux package" issue.

**Comment by ghost** [comment]
llvm-clay-git package can be found in the Archlinux AUR repository. Provides llvm+clang (3.0) patched for Clay compatibility.

(clay-git package coming soon)

**Comment by ghost** [comment]
clay-git package can now be found in the Archlinux AUR repository.

Note: The old clay-hg package has been flagged out-of-date.

**Comment by jckarter** [comment]
Excellent. Nice work @agemogolk.

**Comment by ghost** [comment]
AUR package install fails with issue#147

**Comment by jckarter** [comment]
Does it need to be updated to the current master or anything like that?
